[".vim/pack/alker0/chezmoi.vim"]
    type = "git-repo"
    url = "https://github.com/alker0/chezmoi.vim.git"
    refreshPeriod = "168h"
[".config/setup-scripts/caveman.sh"]
    type = "file"
    url = "https://raw.githubusercontent.com/JuliusBrussee/caveman/main/install.sh"
